include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true,
    avoid_empty_else: true,
    lowercase_with_underscores: true,
    avoid_print: true,
    unnecessary_lambdas: true,
